# action.yml
name: 'Sync 1P Vault to Fly'
description: 'Sync 1Password secrets to a Fly app'
inputs:
  vault:
    description: 'The 1P vault'
    required: true
  fly_app:
    description: 'The fly app'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vault }}
    - ${{ inputs.fly_app }}
