# action.yml
name: 'One Password CLI'
description: 'Convert 1Password secrets to name=value'
inputs:
  vault:
    description: 'The vault to hit'
    required: true
outputs:
  fly_secrets:
    description: 'the fly secrets in name=value format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.vault }}
